name: testing-workflow
on: [push, pull_request]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Setup gssapi for Ubuntu
        run: |
          sudo apt-get install libkrb5-dev
      - name: Install tox-gh-actions
        run: |
          pip install tox-gh-actions
      - name: Test with tox
        run: tox -vv
